### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by gojkovicmilos** [Kloudless/kloudless-js#14]
Hello guys, I love your work, but I noticed a tiny typo in the readme file

![image](https://user-images.githubusercontent.com/50413602/96127110-9801dc80-0ef4-11eb-85ce-4290b72b6921.png)

Thanks for making inter-app compatibility easier!

**Comment by vinodc** [comment]
Thanks for bringing this up @gojkovicmilos ! We've fixed the typo.
