### ISSUE TITLE
Exclude .git from npm package

### ISSUE THREAD

**Issue by jakubstefanski** [Kloudless/kloudless-js#7]
npm fails to install any dependencies when `kloudless@1.1.0` is installed with error:
```
$ npm i whatever
npm ERR! code EISGIT
npm ERR! path /some-project/node_modules/@kloudless/kloudless
npm ERR! git /some-project/node_modules/@kloudless/kloudless: Appears to be a git repo or submodule.
npm ERR! git     /some-project/node_modules/@kloudless/kloudless
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```
and indeed `.git` file is present in npm package:
```
$ ls -a node_modules/@kloudless/kloudless/
.  ..  babel.config.js  CHANGELOG.md  config  dev  dist  .eslintignore  .eslintrc.js  .git  img  lib  LICENSE  .npmignore  package.json  README.MD  REFERENCE.MD  test
```

This problem does not occur in version `1.0.0`.
npm version used: `6.11.3`

**Comment by fsworld009** [comment]
Hi

Thanks for reporting, we have published `v1.1.1` to fix this issue.

You might need to uninstall it first in order to get rid of that `.git` folder

```
npm uninstall @kloudless/kloudless
npm install @kloudless/kloudless
```

The fix is directly pushed to master branch, hence I'll close this issue for now.
Let me know if you have other questions.
